# This is a basic workflow to help you get started with Actions

name: PR Checker

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: CD action
        run: |
          echo "Hello"
