# This is a basic workflow to help you get started with Actions

name: CD Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure-docker-cli
        env:
          DOCKER_CA: ${{ secrets.DOCKER_CA }}
          DOCKER_CERT: ${{ secrets.DOCKER_CERT }}
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
          DOCKER_HOST: "tcp://ec2-35-171-168-3.compute-1.amazonaws.com:2376"
          DOCKER_TLS_VERIFY: "1"
        run: |
          mkdir -pv ~/.docker
          
          echo $DOCKER_CA > ca.pem
          echo $DOCKER_CERT > cert.pem
          echo $DOCKER_KEY > key.pem
          chmod -v 0400 ca-key.pem key.pem server-key.pem
          
          sudo cp ca.pem /usr/local/share/ca-certificates/docker-host.pem
          sudo update-ca-certificates
          
          docker --tlsverify \
            --tlscacert=ca.pem \
            --tlscert=cert.pem \
            --tlskey=key.pem \
            -H=ec2-35-171-168-3.compute-1.amazonaws.com:2376 version
